[[plugins]]
repo = 'Shougo/neocomplcache'
on_i = 1

hook_source = 'source ~/.vim/rc/plugins/neocomplcache.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']

hook_add = 'call yosida95#init#unite#hook_add()'
hook_source = '''
    let g:unite_update_time = 100
    let g:unite_enable_start_insert = 1
    let g:unite_winheight = 15
    let g:unite_enable_auto_select = 0
    let g:unite_force_overwrite_statusline = 0
    au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
    au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = [['n', '<Plug>']]
on_if = "isdirectory(bufname('%'))"

hook_add = '''
    nnoremap <leader>e :VimFilerExplorer<CR>
'''
hook_source = '''
    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_force_overwrite_statusline = 0
'''


[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = [
    'vimproc.vim',
    'vim-quickrun',
    'shabadou.vim',
    'vim-hier',
    'quickfixstatus',
]
on_ft = 'python'

hook_source = '''
    let g:watchdogs_check_BufWritePost_enable = 1
    let g:watchdogs_check_CursorHold_enable = 1

    let g:quickrun_config['watchdogs_checker/_'] = {
        \ 'outputter/quickfix/open_cmd' : '',
        \ }
    let g:quickrun_config['python/watchdogs_checker'] = {
        \ 'type': 'watchdogs_checker/flake8',
        \ }
'''
hook_post_source = 'call watchdogs#setup(g:quickrun_config)'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

hook_source = '''
    let g:jedi#auto_initialization = 1
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#popup_on_dot = 0
    let g:jedi#rename_command = '<Leader>R'
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'Rykka/riv.vim'
on_ft = 'rst'
